version: '3.3'

services:
    backend:
        build: ../
        ports: ['8000:8000']
        env_file: ['../.env']
        depends_on: ['db']
        volumes: ['../:/app']
        environment:
            DB_HOST: db
